### ISSUE TITLE
Create routes for all the features

### ISSUE THREAD

**Issue by tlockcuff** [TLockcuff/node-utilities-server#1]

**Comment by navx2810** [comment]
ref: aabfc3a

I made a feature for a new concept of routing.

In this commit, routes work like this:

folder structure dictates the route
```
    routes/
        image-diff/
            index.route.js
        screenshot/
            index.route.js
        admin/
            new-tool/
                index.route.js
```
becomes
```
    /image-diff
    /screenshot
    /admin/new-tool
```

index.route.js files have methods they can export to hook into this route.
``` typescript
    // Http GET
    export function get(req:Request, res: Response) {} 
    // Http POST
    export function post(req:Request, res: Response) {} 
    // Http PUT
    export function put(req:Request, res: Response) {} 
    // Http DEL
    export function del(req:Request, res: Response) {} 
    // takes any http request
    export function all(req:Request, res: Response) {} 
```

I decided to go with index.route.ts as the file name to look for. route.ts and index.ts are too vague and could match a false positive. 

I also added a quick /help route which display a JSON response containing all the routes and methods available.

What are your thoughts on this?

**Comment by tlockcuff** [comment]
Folders are now routes and the file naming convention all look great. The help route is handly and I'm sure will be useful at some point in time. I'm all for adding helpers to make life easy. I also like how the methods are exported from the route. Looks good!

**Comment by tlockcuff** [comment]
Merged into develop - closing issue
