### ISSUE TITLE
Should we ignore all compiled JS files since VSCode comes with tsc?

### ISSUE THREAD

**Issue by navx2810** [TLockcuff/node-utilities-server#2]
Something to consider:

If so, we can add a folder into tsconfig which indicates where the output of files will go, it mimics the path structure of the ts source.

```
{
   "outDir": "./js"
}
```

Files
```
index.ts
src/
    image-diff/
        index.ts        
```
Becomes
```
js/
    index.js
    src/
        image-diff/
            index.js
```

Scripts would then reference the js/index.js file.
Relative paths would also be fine.

**Comment by tlockcuff** [comment]
Let's go with it, I like that type of structure anyway. I was actually going to ask you how we could either hide or move those compiled js files so there not in the way. Feel free take creative license on this project. As long as we keep it modular in the sense we can add/remove "routes" easily.

**Comment by navx2810** [comment]
Alright. I pushed that change in fd8a26b.

I had to change some of your logic so it looked to /js/... instead of in route.
