### ISSUE TITLE
Screenshots should have meaningful download names?

### ISSUE THREAD

**Issue by navx2810** [TLockcuff/node-utilities-server#3]
ref: c6cd8c90d34a2fc8ff0040cbf2057659195b76d4

I created a feature which has this functionality.

It sets the filename of the downloaded file to
```
[hostname?]_[width]x[height]_screenshot_[date].jpg
```

This will probably be helpful when downloading and archiving these images.

Should this be an included feature?

**Comment by tlockcuff** [comment]
Yes, let's move to that naming convention. There's a good chance the screenshots (and any other asset generated for that matter) will end up being hosted on AWS or some cloud storage. Depending on how often the tool is used, we're going to have a ton of images, all of which I would like to go back in time and see.

**Comment by tlockcuff** [comment]
Merged into develop - closing the issue
