### ISSUE TITLE
Express route validation

### ISSUE THREAD

**Issue by tlockcuff** [TLockcuff/node-utilities-server#7]
I'm toying with a utility to validate requests for sake of reporting missing params, query values, etc...

Here's the npm package: https://github.com/ctavan/express-validator

It's as simple as import the package to index.js and then add `app.use(expressValidator());` right after we initiate the express app().

Then in a route, we can simply write the following to validate required params.

```typescript
req.check('url').exists();

if (req.validationErrors.length > 0) {
     res.status(400).json(JSON.stringify({ errors: req.validationErrors }));
     return;
}
```

If errors do exist, send them back to the user and then return to stop further code from running.

I don't really like the fact of writing this on every single route. I want to come up with some other way to incorporate this into a possible utility helper.

I'd like to to do something like this

```typescript
// res: the route request
// array: required params for the route
// callback: optional function to overwrite the error reporting
validate(res, ['url', 'param2', 'param2'], callback);
```
Validate will run the above code and create a list of "errors" to render back to the client. If everything is kosher then we don't have to worry about anything, the code will just continue. If a callback is passed, the route would then handle the error reporting. If no callback, the validate function with handle everything for you. I'm thinking for more complex error reporting we may want to overwrite logic at some point with the callback.

**Comment by navx2810** [comment]
Good shit. 2 years later!

**Comment by tlockcuff** [comment]
Lol. May or may not have been me playing around. I downloaded the new GitHub app...

**Comment by navx2810** [comment]
GitHub app? Oh damn

**Comment by tlockcuff** [comment]
iOS has the official GitHub one now. Not sure about Android... it’s pretty nice actually. At work, I’m working with another company and their react code is in GitHub. They actually use issues for tracking work. It’s nice to work in legit workflows haha.
